<?php include('config.php'); ?>
<?php include('utils.php'); ?>

<?php

 $cachexml = new SimpleXMLElement($GLOBALS['AllCache'], null, true);
 $xml = new SimpleXMLElement(urlMaker($_POST['urlvar'],$_POST["cmd"],$_POST["val"]), null, true);
 $alk = file_get_contents ( 'alk.html' );

#  	$RBIN=getBin($xml->{'R'});
#       $RON=getBin($xml->{'RON'});
#       $ROFF=getBin($xml->{'ROFF'});
#       $RMASK=applyMasks($xml->{'R'},$xml->{'RON'},$xml->{'ROFF'});

	$RBIN1=getBin($xml->{'R1'});
        $RON1=getBin($xml->{'RON1'});
        $ROFF1=getBin($xml->{'ROFF1'});
	$RMASK1=applyMasks($xml->{'R1'},$xml->{'RON1'},$xml->{'ROFF1'});

  	$RBIN2=getBin($xml->{'R2'});
        $RON2=getBin($xml->{'RON2'});
        $ROFF2=getBin($xml->{'ROFF2'});
	$RMASK2=applyMasks($xml->{'R2'},$xml->{'RON2'},$xml->{'ROFF2'});

  	$RBIN3=getBin($xml->{'R3'});
        $RON3=getBin($xml->{'RON3'});
        $ROFF3=getBin($xml->{'ROFF3'});
	$RMASK3=applyMasks($xml->{'R3'},$xml->{'RON3'},$xml->{'ROFF3'});

        $RBIN4=getBin($xml->{'R4'});
        $RON4=getBin($xml->{'RON4'});
        $ROFF4=getBin($xml->{'ROFF4'});
        $RMASK4=applyMasks($xml->{'R4'},$xml->{'RON4'},$xml->{'ROFF4'});

        $RBIN5=getBin($xml->{'R5'});
        $RON5=getBin($xml->{'RON5'});
        $ROFF5=getBin($xml->{'ROFF5'});
        $RMASK5=applyMasks($xml->{'R5'},$xml->{'RON5'},$xml->{'ROFF5'});

	$relayData = array();
  /*	$relayData["rbin"]=$RBIN;
  	$relayData["relay1val"]=$RBIN[7];
	$relayData["relay2val"]=$RBIN[6];
	$relayData["relay3val"]=$RBIN[5];
	$relayData["relay4val"]=$RBIN[4];
	$relayData["relay5val"]=$RBIN[3];
	$relayData["relay6val"]=$RBIN[2];
	$relayData["relay7val"]=$RBIN[1];
	$relayData["relay8val"]=$RBIN[0];
	$relayData["relay1on"]=$RON[7];
	$relayData["relay2on"]=$RON[6];
	$relayData["relay3on"]=$RON[5];
	$relayData["relay4on"]=$RON[4];
	$relayData["relay5on"]=$RON[3];
	$relayData["relay6on"]=$RON[2];
	$relayData["relay7on"]=$RON[1];
	$relayData["relay8on"]=$RON[0];
	$relayData["relay1off"]=$ROFF[7];
	$relayData["relay2off"]=$ROFF[6];
	$relayData["relay3off"]=$ROFF[5];
	$relayData["relay4off"]=$ROFF[4];
	$relayData["relay5off"]=$ROFF[3];
	$relayData["relay6off"]=$ROFF[2];
	$relayData["relay7off"]=$ROFF[1];
	$relayData["relay8off"]=$ROFF[0];
	$relayData["relay1status"]=$RMASK[7];
	$relayData["relay2status"]=$RMASK[6];
	$relayData["relay3status"]=$RMASK[5];
	$relayData["relay4status"]=$RMASK[4];
	$relayData["relay5status"]=$RMASK[3];
	$relayData["relay6status"]=$RMASK[2];
	$relayData["relay7status"]=$RMASK[1];
	$relayData["relay8status"]=$RMASK[0];
*/
  	$relayData["rbin1"]=$RBIN1;
  	$relayData["relay11val"]=$RBIN1[7];
	$relayData["relay12val"]=$RBIN1[6];
	$relayData["relay13val"]=$RBIN1[5];
	$relayData["relay14val"]=$RBIN1[4];
	$relayData["relay15val"]=$RBIN1[3];
	$relayData["relay16val"]=$RBIN1[2];
	$relayData["relay17val"]=$RBIN1[1];
	$relayData["relay18val"]=$RBIN1[0];
	$relayData["relay11on"]=$RON1[7];
	$relayData["relay12on"]=$RON1[6];
	$relayData["relay13on"]=$RON1[5];
	$relayData["relay14on"]=$RON1[4];
	$relayData["relay15on"]=$RON1[3];
	$relayData["relay16on"]=$RON1[2];
	$relayData["relay17on"]=$RON1[1];
	$relayData["relay18on"]=$RON1[0];
	$relayData["relay11off"]=$ROFF1[7];
	$relayData["relay12off"]=$ROFF1[6];
	$relayData["relay13off"]=$ROFF1[5];
	$relayData["relay14off"]=$ROFF1[4];
	$relayData["relay15off"]=$ROFF1[3];
	$relayData["relay16off"]=$ROFF1[2];
	$relayData["relay17off"]=$ROFF1[1];
	$relayData["relay18off"]=$ROFF1[0];
	$relayData["relay11status"]=$RMASK1[7];
	$relayData["relay12status"]=$RMASK1[6];
	$relayData["relay13status"]=$RMASK1[5];
	$relayData["relay14status"]=$RMASK1[4];
	$relayData["relay15status"]=$RMASK1[3];
	$relayData["relay16status"]=$RMASK1[2];
	$relayData["relay17status"]=$RMASK1[1];
	$relayData["relay18status"]=$RMASK1[0];

  	$relayData["rbin2"]=$RBIN2;
  	$relayData["relay21val"]=$RBIN2[7];
	$relayData["relay22val"]=$RBIN2[6];
	$relayData["relay23val"]=$RBIN2[5];
	$relayData["relay24val"]=$RBIN2[4];
	$relayData["relay25val"]=$RBIN2[3];
	$relayData["relay26val"]=$RBIN2[2];
	$relayData["relay27val"]=$RBIN2[1];
	$relayData["relay28val"]=$RBIN2[0];
	$relayData["relay21on"]=$RON2[7];
	$relayData["relay22on"]=$RON2[6];
	$relayData["relay23on"]=$RON2[5];
	$relayData["relay24on"]=$RON2[4];
	$relayData["relay25on"]=$RON2[3];
	$relayData["relay26on"]=$RON2[2];
	$relayData["relay27on"]=$RON2[1];
	$relayData["relay28on"]=$RON2[0];
	$relayData["relay21off"]=$ROFF2[7];
	$relayData["relay22off"]=$ROFF2[6];
	$relayData["relay23off"]=$ROFF2[5];
	$relayData["relay24off"]=$ROFF2[4];
	$relayData["relay25off"]=$ROFF2[3];
	$relayData["relay26off"]=$ROFF2[2];
	$relayData["relay27off"]=$ROFF2[1];
	$relayData["relay28off"]=$ROFF2[0];
	$relayData["relay21status"]=$RMASK2[7];
	$relayData["relay22status"]=$RMASK2[6];
	$relayData["relay23status"]=$RMASK2[5];
	$relayData["relay24status"]=$RMASK2[4];
	$relayData["relay25status"]=$RMASK2[3];
	$relayData["relay26status"]=$RMASK2[2];
	$relayData["relay27status"]=$RMASK2[1];
	$relayData["relay28status"]=$RMASK2[0];

  	$relayData["rbin3"]=$RBIN3;
  	$relayData["relay31val"]=$RBIN3[7];
	$relayData["relay32val"]=$RBIN3[6];
	$relayData["relay33val"]=$RBIN3[5];
	$relayData["relay34val"]=$RBIN3[4];
	$relayData["relay35val"]=$RBIN3[3];
	$relayData["relay36val"]=$RBIN3[2];
	$relayData["relay37val"]=$RBIN3[1];
	$relayData["relay38val"]=$RBIN3[0];
	$relayData["relay31on"]=$RON3[7];
	$relayData["relay32on"]=$RON3[6];
	$relayData["relay33on"]=$RON3[5];
	$relayData["relay34on"]=$RON3[4];
	$relayData["relay35on"]=$RON3[3];
	$relayData["relay36on"]=$RON3[2];
	$relayData["relay37on"]=$RON3[1];
	$relayData["relay38on"]=$RON3[0];
	$relayData["relay31off"]=$ROFF3[7];
	$relayData["relay32off"]=$ROFF3[6];
	$relayData["relay33off"]=$ROFF3[5];
	$relayData["relay34off"]=$ROFF3[4];
	$relayData["relay35off"]=$ROFF3[3];
	$relayData["relay36off"]=$ROFF3[2];
	$relayData["relay37off"]=$ROFF3[1];
	$relayData["relay38off"]=$ROFF3[0];
	$relayData["relay31status"]=$RMASK3[7];
	$relayData["relay32status"]=$RMASK3[6];
	$relayData["relay33status"]=$RMASK3[5];
	$relayData["relay34status"]=$RMASK3[4];
	$relayData["relay35status"]=$RMASK3[3];
	$relayData["relay36status"]=$RMASK3[2];
	$relayData["relay37status"]=$RMASK3[1];
	$relayData["relay38status"]=$RMASK3[0];

        $relayData["rbin4"]=$RBIN4;
        $relayData["relay41val"]=$RBIN4[7];
        $relayData["relay42val"]=$RBIN4[6];
        $relayData["relay43val"]=$RBIN4[5];
        $relayData["relay44val"]=$RBIN4[4];
        $relayData["relay45val"]=$RBIN4[3];
        $relayData["relay46val"]=$RBIN4[2];
        $relayData["relay47val"]=$RBIN4[1];
        $relayData["relay48val"]=$RBIN4[0];
        $relayData["relay41on"]=$RON4[7];
        $relayData["relay42on"]=$RON4[6];
        $relayData["relay43on"]=$RON4[5];
        $relayData["relay44on"]=$RON4[4];
        $relayData["relay45on"]=$RON4[3];
        $relayData["relay46on"]=$RON4[2];
        $relayData["relay47on"]=$RON4[1];
        $relayData["relay48on"]=$RON4[0];
        $relayData["relay41off"]=$ROFF4[7];
        $relayData["relay42off"]=$ROFF4[6];
        $relayData["relay43off"]=$ROFF4[5];
        $relayData["relay44off"]=$ROFF4[4];
        $relayData["relay45off"]=$ROFF4[3];
        $relayData["relay46off"]=$ROFF4[2];
        $relayData["relay47off"]=$ROFF4[1];
        $relayData["relay48off"]=$ROFF4[0];
        $relayData["relay41status"]=$RMASK4[7];
        $relayData["relay42status"]=$RMASK4[6];
        $relayData["relay43status"]=$RMASK4[5];
        $relayData["relay44status"]=$RMASK4[4];
        $relayData["relay45status"]=$RMASK4[3];
        $relayData["relay46status"]=$RMASK4[2];
        $relayData["relay47status"]=$RMASK4[1];
        $relayData["relay48status"]=$RMASK4[0];

        $relayData["rbin5"]=$RBIN5;
        $relayData["relay51val"]=$RBIN5[7];
        $relayData["relay52val"]=$RBIN5[6];
        $relayData["relay53val"]=$RBIN5[5];
        $relayData["relay54val"]=$RBIN5[4];
        $relayData["relay55val"]=$RBIN5[3];
        $relayData["relay56val"]=$RBIN5[2];
        $relayData["relay57val"]=$RBIN5[1];
        $relayData["relay58val"]=$RBIN5[0];
        $relayData["relay51on"]=$RON5[7];
        $relayData["relay52on"]=$RON5[6];
        $relayData["relay53on"]=$RON5[5];
        $relayData["relay54on"]=$RON5[4];
        $relayData["relay55on"]=$RON5[3];
        $relayData["relay56on"]=$RON5[2];
        $relayData["relay57on"]=$RON5[1];
        $relayData["relay58on"]=$RON5[0];
        $relayData["relay51off"]=$ROFF5[7];
        $relayData["relay52off"]=$ROFF5[6];
        $relayData["relay53off"]=$ROFF5[5];
        $relayData["relay54off"]=$ROFF5[4];
        $relayData["relay55off"]=$ROFF5[3];
        $relayData["relay56off"]=$ROFF5[2];
        $relayData["relay57off"]=$ROFF5[1];
        $relayData["relay58off"]=$ROFF5[0];
        $relayData["relay51status"]=$RMASK5[7];
        $relayData["relay52status"]=$RMASK5[6];
        $relayData["relay53status"]=$RMASK5[5];
        $relayData["relay54status"]=$RMASK5[4];
        $relayData["relay55status"]=$RMASK5[3];
        $relayData["relay56status"]=$RMASK5[2];
        $relayData["relay57status"]=$RMASK5[1];
        $relayData["relay58status"]=$RMASK5[0];

  $ra_mem_full = $cachexml->{'MEM'};
  $ra_mem_full = (string)$ra_mem_full;

$FullVarsStart=100;

$memData = array();
$memData["Mem_B_MoonOffset"]=readByte(100-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_Vacation"]=readByte(101-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AutoFeed"]=readByte(102-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AutoFeedPress"]=readByte(103-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AutoFeedRepeat"]=readByte(104-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AutoFeedOffset"]=readByte(105-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_WCFillTime"]=readInt(106-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_Latitude"]=readInt(108-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_Longitude"]=readInt(110-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AcclRiseOffset"]=readByte(112-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AcclSetOffset"]=readByte(113-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AcclDay"]=readByte(114-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_SwabbieRepeat"]=readByte(115-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_SwabbieTime"]=readByte(116-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_TideMin"]=readByte(117-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_TideMax"]=readByte(118-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_PumpOffset"]=readByte(119-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_FeedingRF"]=readByte(120-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_NightRF"]=readByte(121-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_NightSpeed"]=readByte(122-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_NightDuration"]=readByte(123-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_NTMSpeed"]=readByte(124-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_NTMDuration"]=readByte(125-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_NTMDelay"]=readByte(126-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_NTMTime"]=readByte(127-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_CalDP1Vol"]=readInt(128-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_CalDP1Time"]=readInt(130-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_DP1Volume"]=readInt(132-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_CalDP2Vol"]=readInt(134-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_CalDP2Time"]=readInt(136-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_DP2Volume"]=readInt(138-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_LogATO"]=readByte(140-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_LogPrevATO"]=readByte(141-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AlkMaxDelta"]=readByte(142-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_TideMode"]=readByte(143-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintGAC"]=readByte(144-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintGFO"]=readByte(145-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintCal"]=readByte(146-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintAlk"]=readByte(147-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintWC"]=readByte(148-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintATO"]=readByte(149-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintFeeding"]=readByte(150-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintSkimmer"]=readByte(151-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintSocks"]=readByte(152-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintWCVol"]=readByte(153-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_CalDP3Vol"]=readInt(154-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_CalDP3Time"]=readInt(156-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_DP3Volume"]=readInt(158-$FullVarsStart,$ra_mem_full);

$memData["Mem_B_LightMode"]=readByte(160-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_LightOffset"]=readByte(161-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_RiseOffset"]=readInt(162-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_SetOffset"]=readInt(164-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AcclActinicOffset"]=readByte(166-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AcclDaylightOffset"]=readByte(167-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_RandomMode"]=readByte(168-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_GyreOffset"]=readByte(169-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MoonMode"]=readByte(170-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_LightsOffPerc"]=readByte(171-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_FeedingSpeed"]=readByte(172-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_WCSpeed"]=readByte(173-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AlkTarget"]=readByte(174-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_PowerOutageSpeed"]=readByte(175-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_VinegarWeek"]=readByte(176-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_MaintVinegar"]=readByte(177-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_EnableStorm"]=readByte(178-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_ForceRandomTide"]=readByte(179-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_AWCTime"]=readInt(180-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_AWCFrequency"]=readInt(182-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_AWCOffset"]=readInt(184-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_MixTime"]=readInt(186-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_MixFrequency"]=readInt(188-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_FlushTime"]=readByte(190-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_DP1Log"]=readInt(191-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_DP2Log"]=readInt(193-$FullVarsStart,$ra_mem_full);
$memData["Mem_I_DP3Log"]=readInt(195-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AlkAdjVol"]=readByte(197-$FullVarsStart,$ra_mem_full);
$memData["Mem_B_AlkAdjDelta"]=readByte(198-$FullVarsStart,$ra_mem_full);

$memData["Mem_B_ResetMemory"]=readByte(199-$FullVarsStart,$ra_mem_full);
$FullVarsEnd=200;

$VarsStart=100; // correct for php file
$memData["Mem_B_MHOnHour"]=readByte($VarsStart,$ra_mem_full);
$memData["Mem_B_MHOnMinute"]=readByte($VarsStart+1,$ra_mem_full);
$memData["Mem_B_MHOffHour"]=readByte($VarsStart+2,$ra_mem_full);
$memData["Mem_B_MHOffMinute"]=readByte($VarsStart+3,$ra_mem_full);
$memData["Mem_B_StdLightsOnHour"]=readByte($VarsStart+4,$ra_mem_full);
$memData["Mem_B_StdLightsOnMinute"]=readByte($VarsStart+5,$ra_mem_full);
$memData["Mem_B_StdLightsOffHour"]=readByte($VarsStart+6,$ra_mem_full);
$memData["Mem_B_StdLightsOffMinute"]=readByte($VarsStart+7,$ra_mem_full);
$memData["Mem_I_WM1Timer"]=readInt($VarsStart+8,$ra_mem_full);
$memData["Mem_I_WM2Timer"]=readInt($VarsStart+10,$ra_mem_full);
$memData["Mem_B_DP1Timer"]=readByte($VarsStart+12,$ra_mem_full);
$memData["Mem_B_DP2Timer"]=readByte($VarsStart+13,$ra_mem_full);
$memData["Mem_I_FeedingTimer"]=readInt($VarsStart+14,$ra_mem_full);
$memData["Mem_I_LCDTimer"]=readInt($VarsStart+16,$ra_mem_full);
$memData["Mem_I_OverheatTemp"]=readInt($VarsStart+18,$ra_mem_full);
$memData["Mem_B_LEDPWMDaylight"]=readByte($VarsStart+20,$ra_mem_full);
$memData["Mem_B_LEDPWMActinic"]=readByte($VarsStart+21,$ra_mem_full);
$memData["Mem_I_HeaterTempOn"]=readInt($VarsStart+22,$ra_mem_full);
$memData["Mem_I_HeaterTempOff"]=readInt($VarsStart+24,$ra_mem_full);
$memData["Mem_I_ChillerTempOn"]=readInt($VarsStart+26,$ra_mem_full);
$memData["Mem_I_ChillerTempOff"]=readInt($VarsStart+28,$ra_mem_full);
$memData["Mem_B_ATOTimeout"]=readByte($VarsStart+30,$ra_mem_full);
$memData["Mem_I_PHMax"]=readInt($VarsStart+31,$ra_mem_full);
$memData["Mem_I_PHMin"]=readInt($VarsStart+33,$ra_mem_full);
$memData["Mem_B_MHDelay"]=readByte($VarsStart+35,$ra_mem_full);
$memData["Mem_B_DP1OnHour"]=readByte($VarsStart+36,$ra_mem_full);
$memData["Mem_B_DP1OnMinute"]=readByte($VarsStart+37,$ra_mem_full);
$memData["Mem_B_DP2OnHour"]=readByte($VarsStart+38,$ra_mem_full);
$memData["Mem_B_DP2OnMinute"]=readByte($VarsStart+39,$ra_mem_full);
$memData["Mem_B_ATOHourInterval"]=readByte($VarsStart+40,$ra_mem_full);
$memData["Mem_B_ATOHighHourInterval"]=readByte($VarsStart+41,$ra_mem_full);
$memData["Mem_B_ATOHighTimeout"]=readByte($VarsStart+42,$ra_mem_full);
$memData["Mem_I_DP1RepeatInterval"]=readInt($VarsStart+43,$ra_mem_full);
$memData["Mem_I_DP2RepeatInterval"]=readInt($VarsStart+45,$ra_mem_full);
$memData["Mem_I_SalMax"]=readInt($VarsStart+47,$ra_mem_full);
$memData["Mem_B_PWMSlopeStartD"]=readByte($VarsStart+49,$ra_mem_full);
$memData["Mem_B_PWMSlopeEndD"]=readByte($VarsStart+50,$ra_mem_full);
$memData["Mem_B_PWMSlopeDurationD"]=readByte($VarsStart+51,$ra_mem_full);
$memData["Mem_B_PWMSlopeStartA"]=readByte($VarsStart+52,$ra_mem_full);
$memData["Mem_B_PWMSlopeEndA"]=readByte($VarsStart+53,$ra_mem_full);
$memData["Mem_B_PWMSlopeDurationA"]=readByte($VarsStart+54,$ra_mem_full);
$memData["Mem_B_RFMode"]=readByte($VarsStart+55,$ra_mem_full);
$memData["Mem_B_RFSpeed"]=readByte($VarsStart+56,$ra_mem_full);
$memData["Mem_B_RFDuration"]=readByte($VarsStart+57,$ra_mem_full);
$memData["Mem_B_PWMSlopeStart0"]=readByte($VarsStart+58,$ra_mem_full);
$memData["Mem_B_PWMSlopeEnd0"]=readByte($VarsStart+59,$ra_mem_full);
$memData["Mem_B_PWMSlopeDuration0"]=readByte($VarsStart+60,$ra_mem_full);
$memData["Mem_B_PWMSlopeStart1"]=readByte($VarsStart+61,$ra_mem_full);
$memData["Mem_B_PWMSlopeEnd1"]=readByte($VarsStart+62,$ra_mem_full);
$memData["Mem_B_PWMSlopeDuration1"]=readByte($VarsStart+63,$ra_mem_full);
$memData["Mem_B_PWMSlopeStart2"]=readByte($VarsStart+64,$ra_mem_full);
$memData["Mem_B_PWMSlopeEnd2"]=readByte($VarsStart+65,$ra_mem_full);
$memData["Mem_B_PWMSlopeDuration2"]=readByte($VarsStart+66,$ra_mem_full);
$memData["Mem_B_PWMSlopeStart3"]=readByte($VarsStart+67,$ra_mem_full);
$memData["Mem_B_PWMSlopeEnd3"]=readByte($VarsStart+68,$ra_mem_full);
$memData["Mem_B_PWMSlopeDuration3"]=readByte($VarsStart+69,$ra_mem_full);
$memData["Mem_B_PWMSlopeStart4"]=readByte($VarsStart+70,$ra_mem_full);
$memData["Mem_B_PWMSlopeEnd4"]=readByte($VarsStart+71,$ra_mem_full);
$memData["Mem_B_PWMSlopeDuration4"]=readByte($VarsStart+72,$ra_mem_full);
$memData["Mem_B_PWMSlopeStart5"]=readByte($VarsStart+73,$ra_mem_full);
$memData["Mem_B_PWMSlopeEnd5"]=readByte($VarsStart+74,$ra_mem_full);
$memData["Mem_B_PWMSlopeDuration5"]=readByte($VarsStart+75,$ra_mem_full);
$memData["Mem_I_ATOExtendedTimeout"]=readInt($VarsStart+76,$ra_mem_full);
$memData["Mem_I_ATOHighExtendedTimeout"]=readInt($VarsStart+78,$ra_mem_full);
$memData["Mem_I_ORPMin"]=readInt($VarsStart+80,$ra_mem_full);
$memData["Mem_I_ORPMax"]=readInt($VarsStart+82,$ra_mem_full);
$memData["Mem_B_ActinicOffset"]=readByte($VarsStart+84,$ra_mem_full);
$memData["Mem_I_CO2ControlOn"]=readInt($VarsStart+85,$ra_mem_full);
$memData["Mem_I_CO2ControlOff"]=readInt($VarsStart+87,$ra_mem_full);
$memData["Mem_I_PHControlOn"]=readInt($VarsStart+89,$ra_mem_full);
$memData["Mem_I_PHControlOff"]=readInt($VarsStart+91,$ra_mem_full);
$memData["Mem_B_AISlopeStartW"]=readByte($VarsStart+93,$ra_mem_full);
$memData["Mem_B_AISlopeEndW"]=readByte($VarsStart+94,$ra_mem_full);
$memData["Mem_B_AISlopeDurationW"]=readByte($VarsStart+95,$ra_mem_full);
$memData["Mem_B_AISlopeStartB"]=readByte($VarsStart+96,$ra_mem_full);
$memData["Mem_B_AISlopeEndB"]=readByte($VarsStart+97,$ra_mem_full);
$memData["Mem_B_AISlopeDurationB"]=readByte($VarsStart+98,$ra_mem_full);
$memData["Mem_B_AISlopeStartRB"]=readByte($VarsStart+99,$ra_mem_full);
$memData["Mem_B_AISlopeEndRB"]=readByte($VarsStart+100,$ra_mem_full);
$memData["Mem_B_AISlopeDurationRB"]=readByte($VarsStart+101,$ra_mem_full);
$memData["Mem_B_RadionSlopeStartW"]=readByte($VarsStart+102,$ra_mem_full);
$memData["Mem_B_RadionSlopeEndW"]=readByte($VarsStart+103,$ra_mem_full);
$memData["Mem_B_RadionSlopeDurationW"]=readByte($VarsStart+104,$ra_mem_full);
$memData["Mem_B_RadionSlopeStartRB"]=readByte($VarsStart+105,$ra_mem_full);
$memData["Mem_B_RadionSlopeEndRB"]=readByte($VarsStart+106,$ra_mem_full);
$memData["Mem_B_RadionSlopeDurationRB"]=readByte($VarsStart+107,$ra_mem_full);
$memData["Mem_B_RadionSlopeStartR"]=readByte($VarsStart+108,$ra_mem_full);
$memData["Mem_B_RadionSlopeEndR"]=readByte($VarsStart+109,$ra_mem_full);
$memData["Mem_B_RadionSlopeDurationR"]=readByte($VarsStart+110,$ra_mem_full);
$memData["Mem_B_RadionSlopeStartG"]=readByte($VarsStart+111,$ra_mem_full);
$memData["Mem_B_RadionSlopeEndG"]=readByte($VarsStart+112,$ra_mem_full);
$memData["Mem_B_RadionSlopeDurationG"]=readByte($VarsStart+113,$ra_mem_full);
$memData["Mem_B_RadionSlopeStartB"]=readByte($VarsStart+114,$ra_mem_full);
$memData["Mem_B_RadionSlopeEndB"]=readByte($VarsStart+115,$ra_mem_full);
$memData["Mem_B_RadionSlopeDurationB"]=readByte($VarsStart+116,$ra_mem_full);
$memData["Mem_B_RadionSlopeStartI"]=readByte($VarsStart+117,$ra_mem_full);
$memData["Mem_B_RadionSlopeEndI"]=readByte($VarsStart+118,$ra_mem_full);
$memData["Mem_B_RadionSlopeDurationI"]=readByte($VarsStart+119,$ra_mem_full);
$memData["Mem_B_DelayedStart"]=readByte($VarsStart+120,$ra_mem_full);
$memData["Mem_I_PHExpMin"]=readInt($VarsStart+121,$ra_mem_full);
$memData["Mem_I_PHExpMax"]=readInt($VarsStart+123,$ra_mem_full);
$memData["Mem_I_WaterLevelMin"]=readInt($VarsStart+125,$ra_mem_full);
$memData["Mem_I_WaterLevelMax"]=readInt($VarsStart+127,$ra_mem_full);
$memData["Mem_I_SalTempComp"]=readInt($VarsStart+129,$ra_mem_full);
$memData["Mem_B_WaterLevelLow"]=readByte($VarsStart+131,$ra_mem_full);
$memData["Mem_B_WaterLevelHigh"]=readByte($VarsStart+132,$ra_mem_full);
$memData["Mem_B_DP3Timer"]=readByte($VarsStart+133,$ra_mem_full);
$memData["Mem_I_DP3RepeatInterval"]=readInt($VarsStart+134,$ra_mem_full);
$memData["Mem_B_LCDID"]=readByte($VarsStart+136,$ra_mem_full);
$memData["Mem_B_DCPumpMode"]=readByte($VarsStart+137,$ra_mem_full);
$memData["Mem_B_DCPumpSpeed"]=readByte($VarsStart+138,$ra_mem_full);
$memData["Mem_B_DCPumpDuration"]=readByte($VarsStart+139,$ra_mem_full);
$memData["Mem_I_WaterLevel1Min"]=readInt($VarsStart+140,$ra_mem_full);
$memData["Mem_I_WaterLevel1Max"]=readInt($VarsStart+142,$ra_mem_full);
$memData["Mem_I_WaterLevel2Min"]=readInt($VarsStart+144,$ra_mem_full);
$memData["Mem_I_WaterLevel2Max"]=readInt($VarsStart+146,$ra_mem_full);
$memData["Mem_I_WaterLevel3Min"]=readInt($VarsStart+148,$ra_mem_full);
$memData["Mem_I_WaterLevel3Max"]=readInt($VarsStart+150,$ra_mem_full);
$memData["Mem_I_WaterLevel4Min"]=readInt($VarsStart+152,$ra_mem_full);
$memData["Mem_I_WaterLevel4Max"]=readInt($VarsStart+154,$ra_mem_full);
$memData["Mem_B_LEDPWMDaylight2"]=readByte($VarsStart+156,$ra_mem_full);
$memData["Mem_B_LEDPWMActinic2"]=readByte($VarsStart+157,$ra_mem_full);
$memData["Mem_B_PWMSlopeStartD2"]=readByte($VarsStart+158,$ra_mem_full);
$memData["Mem_B_PWMSlopeEndD2"]=readByte($VarsStart+159,$ra_mem_full);
$memData["Mem_B_PWMSlopeDurationD2"]=readByte($VarsStart+160,$ra_mem_full);
$memData["Mem_B_PWMSlopeStartA2"]=readByte($VarsStart+161,$ra_mem_full);
$memData["Mem_B_PWMSlopeEndA2"]=readByte($VarsStart+162,$ra_mem_full);
$memData["Mem_B_PWMSlopeDurationA2"]=readByte($VarsStart+163,$ra_mem_full);
$memData["Mem_B_DCPumpThreshold"]=readByte($VarsStart+164,$ra_mem_full);
$memData["Mem_I_PHEControlOn"]=readInt($VarsStart+165,$ra_mem_full);
$memData["Mem_I_PHEControlOff"]=readInt($VarsStart+167,$ra_mem_full);
$VarsEnd=$VarsStart+169;

$info = array();
$info["USAGE"]=$xml->{'C6'} > 0 ? round(($xml->{'WL'}-10)/$xml->{'C6'}) : "INF";
#$info["SUNRISE"]=$memData["Mem_B_StdLightsOnHour"]-($memData["Mem_B_ActinicOffset"]/60) . ':' . $memData["Mem_B_StdLightsOnMinute"];
#$info["SUNSET"]=$memData["Mem_B_StdLightsOffHour"]+($memData["Mem_B_ActinicOffset"]/60) . ':' . $memData["Mem_B_StdLightsOffMinute"];
$RISE_HOUR=$memData["Mem_B_StdLightsOnHour"]-($memData["Mem_B_ActinicOffset"]/60);
if ($RISE_HOUR < 0 ) { $RISE_HOUR=$RISE_HOUR+24; }
$SET_HOUR=$memData["Mem_B_StdLightsOffHour"]+($memData["Mem_B_ActinicOffset"]/60);
if ($SET_HOUR > 23 ) { $SET_HOUR=$SET_HOUR-23; }
$info["SUNRISE"]=$RISE_HOUR . ':' . $memData["Mem_B_StdLightsOnMinute"];
$info["SUNSET"]=$SET_HOUR . ':' . $memData["Mem_B_StdLightsOffMinute"];
$info["DP1Rate"]=number_format(($memData["Mem_I_CalDP1Vol"] / $memData["Mem_I_CalDP1Time"] * 60),2);
$info["DP2Rate"]=number_format(($memData["Mem_I_CalDP2Vol"] / $memData["Mem_I_CalDP2Time"] * 60),2);
$info["DP3Rate"]=number_format(($memData["Mem_I_CalDP3Vol"] / $memData["Mem_I_CalDP3Time"] * 60),2);

      $values = array(
      "Constant"=>"0",
      "Lagoon"=>"1",
      "Reef Crest"=>"2",
      "Short Pulse"=>"3",
      "Long Pulse"=>"4",
      "Smart NTM"=>"5",
      "Tidal Swell"=>"6",
      "Feeding"=>"7",
      "Night"=>"9",
      "Storm"=>"10",
      "Custom"=>"11",
      );

      foreach ($values as $key => $value) {
        if ( $value == $memData["Mem_B_RFMode"] ) {
          $info["RFMODE"]=$key;
        }
      }

      $tidevalues = array(
	"ReefCrest"=>"0",
        "TidalSwell"=>"1",
        "Smart_NTM"=>"2",
        "Lagoon"=>"3",
        "Short Pulse"=>"4",
        "Long Pulse"=>"5",
        "BHazard"=>"6",
        "Else"=>"7",
        "Sine"=>"8",
        "Constant"=>"9"
      );

      foreach ($tidevalues as $key => $value) {
        if ( $value == $memData["Mem_B_TideMode"] ) {
          $info["CUSTOMMODE"]=$key;
        }
      }

$return = array();
$return["xml"] = $xml;
$return["info"] = $info;
$return["mem"] = $memData;
$return["relays"] = $relayData;
$return["alk"] = $alk;

echo json_encode($return);
?>
